name: CD - Latest Development
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  dev-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build Project
      env:
        REACT_APP_AGORA_APP_ID: "${{ secrets.AGORA_APP_ID }}"
        REACT_APP_AGORA_APP_CERTIFICATE: "${{ secrets.AGORA_APP_CERTIFICATE }}"
      run: |
        yarn install
        yarn run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWD }}
        protocol: ftps
        local-dir: ./build/
        server-dir: ./
