name: CD - Latest Main Branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dev-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build Project
      env:
        REACT_APP_AGORA_APP_ID: "${{ secrets.AGORA_APP_ID }}"
        REACT_APP_AGORA_APP_CERTIFICATE: "${{ secrets.AGORA_APP_CERTIFICATE }}"
      run: |
        yarn install
        yarn run build
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Sync files
      run: |
        rsync -avz ./build/ ${{ secrets.SSH_RSYNC_TARGET }}